import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./editorjs.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "App Todo Pro",
  description: "Generated by create next app",
};

import Sidebar from "./Sidebar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50`}>
        <div className="flex">
          <Sidebar />
          <div className="flex-1 ml-56 min-h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
